[package]
name = "air"
version = "0.1.0"
edition = "2021"
authors = ["Damilare Akinlaja <dreakinlaja@gmail.com>"]
license = "MIT"
description = "AIR - ASH Immediate Respresentation"
keywords = ["IR", "JIT", "Compiler"]

[dependencies]
inkwell = {workspace=true}
anyhow = {workspace=true}