[package]
name = "air"
version = "0.1.0"
edition = "2021"
authors = ["Damilare Akinlaja <dreakinlaja@gmail.com>"]
license = "MIT"
description = "AIR - ASH Intermediate Representation (bytecode optimizer)"
keywords = ["IR", "JIT", "Compiler", "Optimizer"]

[dependencies]
anyhow = {workspace=true}
